mapping *dest = ({
 ([ "name":"yilihe",
           "context": ({
"/d/xingxiu/yili",
"/d/xingxiu/shanjiao",
"/d/xingxiu/silk9",
"/d/xingxiu/silk8",
"/d/xingxiu/silk7",
"/d/xingxiu/silk6",
"/d/xingxiu/silk5",
"/d/xingxiu/silk4",
"/d/xingxiu/silk3",
"/d/xingxiu/silk2",
"/d/xingxiu/silk1",
"/d/xingxiu/silk",
})]),

 ([ "name":"jygw",
           "context": ({
"/d/xingxiu/silk",
"/d/xingxiu/silk1",
"/d/xingxiu/silk2",
"/d/xingxiu/silk3",
"/d/xingxiu/silk4",
"/d/xingxiu/silk5",
"/d/xingxiu/silk6",
"/d/xingxiu/silk7",
"/d/xingxiu/silk8",
"/d/xingxiu/silk9",
"/d/xingxiu/shanjiao",
"/d/xingxiu/yili",
})]),
([ "name":"silk",
           "context": ({
"/d/xingxiu/silk1",
"/d/xingxiu/silk2",
"/d/xingxiu/silk3",
"/d/xingxiu/silk4",
"/d/xingxiu/silk5a",
"/d/xingxiu/silk7a",
"/d/xingxiu/silk7",
"/d/xingxiu/silk8",
"/d/xingxiu/silk9",
"/d/xingxiu/shanjiao",
"/d/xingxiu/yili",
})]),
([ "name":"silk1b",
           "context": ({
"/d/xingxiu/silk1",
"/d/xingxiu/silk2",
"/d/xingxiu/silk3",
"/d/xingxiu/silk3a",
"/d/xingxiu/silk3b",
"/d/xingxiu/silk3c",
"/d/xingxiu/silk7a",
"/d/xingxiu/silk7",
"/d/xingxiu/silk8",
"/d/xingxiu/silk10",
"/d/xingxiu/yili",
})]),
([ "name":"yili",
           "context": ({
"/d/xingxiu/silk10",
"/d/xingxiu/silk8",
"/d/xingxiu/silk7",
"/d/xingxiu/silk7a",
"/d/xingxiu/silk5a",
"/d/xingxiu/silk4",
"/d/xingxiu/silk3",
"/d/xingxiu/silk2",
"/d/xingxiu/silk1",
"/d/xingxiu/silk1a",
"/d/xingxiu/silk1b",
"/d/xingxiu/silk",
})]),
([ "name":"shanjiao",
           "context": ({
"/d/xingxiu/silk9",
"/d/xingxiu/silk8",
"/d/xingxiu/silk7",
"/d/xingxiu/silk7a",
"/d/xingxiu/silk3c",
"/d/xingxiu/silk3b",
"/d/xingxiu/silk3a",
"/d/xingxiu/silk3",
"/d/xingxiu/silk2",
"/d/xingxiu/silk1",
"/d/xingxiu/silk",
})]),
([ "name":"silk5b",
           "context": ({
"/d/xingxiu/silk5",
"/d/xingxiu/silk5a",
"/d/xingxiu/silk7a",
"/d/xingxiu/silk3c",
"/d/xingxiu/silk3b",
"/d/xingxiu/silk3a",
"/d/xingxiu/silk3",
"/d/xingxiu/silk2",
"/d/xingxiu/silk1",
"/d/xingxiu/silk1a",
"/d/xingxiu/silk1b",
"/d/xingxiu/silk",
})]),
([ "name":"silk3a",
           "context": ({
"/d/xingxiu/silk3b",
"/d/xingxiu/silk3c",
"/d/xingxiu/silk7a",
"/d/xingxiu/silk5a",
"/d/xingxiu/silk5",
"/d/xingxiu/silk6",
"/d/xingxiu/silk7",
"/d/xingxiu/silk8",
"/d/xingxiu/silk9",
"/d/xingxiu/shanjiao",
"/d/xingxiu/yili",
})]),
([ "name":"silk8",
           "context": ({
"/d/xingxiu/silk7",
"/d/xingxiu/silk6",
"/d/xingxiu/silk5",
"/d/xingxiu/silk5a",
"/d/xingxiu/silk7a",
"/d/xingxiu/silk3c",
"/d/xingxiu/silk3b",
"/d/xingxiu/silk3a",
"/d/xingxiu/silk3",
"/d/xingxiu/silk2",
"/d/xingxiu/silk1",
"/d/xingxiu/silk",
})]),

});

