// By River@SJ 2002.2.25
mapping *npc_skills = ({
([	"family":	"∂Î·“≈…", //1-em1
	"force" :	"linji-zhuang",
	"dodge" :	"anying-fuxiang",
	"parry": 	"huifeng-jian",
	"sword" :	"huifeng-jian",
	"hand" :	"jieshou-jiushi",
	"difficult":	3,
	"team":		0,
]),
([	"family":	"∂Î·“≈…", //2-em2
	"force" :	"linji-zhuang",
	"dodge" :	"anying-fuxiang",
	"parry": 	"yanxing-daofa",
	"blade" :	"yanxing-daofa",
	"strike" : 	"sixiang-zhang",
	"difficult":	2,
	"team":		1,
]),
([	"family":	"ÿ§∞Ô", //3-gb1
	"force" :	"huntian-qigong",
	"dodge" :	"xiaoyaoyou",
	"parry":	"dagou-bang",
	"stick" :	"dagou-bang",
	"strike" : 	"xianglong-zhang",
	"difficult":	3,
	"team":		2,
]),
([	"family":	"ÿ§∞Ô", //4-gb2
	"force" :	"huntian-qigong",
	"dodge" :	"xiaoyaoyou",
	"parry":	"dagou-bang",
	"stick" :	"dagou-bang",
	"strike" : 	"lianhua-zhang",
	"difficult":	2,
	"team":		3,
]),
([	"family":	"ÿ§∞Ô", //5-gb3
	"force" :	"huntian-qigong",
	"dodge" :	"xiaoyaoyou",
	"parry":	"liuhe-daofa",
	"blade" :	"liuhe-daofa",
	"hand" :	"suohou-shou",
	"difficult":	1,
	"team":		4,
]),
([	"family":	"ÿ§∞Ô", //6-gb4
	"force" :	"huntian-qigong",
	"dodge" :	"xiaoyaoyou",
	"parry":	"fengmo-zhang",
	"staff" :	"fengmo-zhang",
	"strike" : 	"lianhua-zhang",
	"difficult":	1,
	"team":		5,
]),
([	"family":	"ÿ§∞Ô", //7-gb5
	"force" :	"huntian-qigong",
	"dodge" :	"xiaoyaoyou",
	"parry":	"huifeng-bian",
	"whip" : 	"huifeng-bian",
	"hand" :	"suohou-shou",
	"difficult":	1,
	"team":		6,
]),
([	"family":	"ÿ§∞Ô", //8-gb6
	"force" :	"huntian-qigong",
	"dodge" :	"xiaoyaoyou",
	"parry":	"fengmo-zhang",
	"staff" :	"fengmo-zhang",
	"strike" : 	"xianglong-zhang",
	"difficult":	2,
	"team":		7,
]),
([	"family":	"π≈ƒπ≈…", //9-gm1
	"force" :	"yunu-xinjing",
	"dodge" :	"yunu-shenfa",
	"parry":	"xuantie-jianfa",
	"sword" :	"xuantie-jianfa",
	"strike" : 	"anran-zhang",
	"difficult":	3,
	"team":		8,
]),
([	"family":	"π≈ƒπ≈…", //10-gm2
	"force" :	"yunu-xinjing",
	"dodge" :	"yunu-shenfa",
	"parry":	"quanzhen-jianfa",
	"sword" :	"quanzhen-jianfa",
	"hand" : 	"tianluo-diwang",
	"difficult":	1,
	"team":		9,
]),
([	"family":	"π≈ƒπ≈…", //11-gm3
	"force" :	"yunu-xinjing",
	"dodge" :	"yunu-shenfa",
	"parry":	"yinsuo-jinling",
	"whip" :	"yinsuo-jinling",
	"cuff" : 	"meinu-quanfa",
	"difficult":	3,
	"team":		10,
]),
([	"family":	"π≈ƒπ≈…", //12-gm4
	"force" :	"yunu-xinjing",
	"dodge" :	"yunu-shenfa",
	"parry":	"yunu-jianfa",
	"sword" :	"yunu-jianfa",
	"cuff" : 	"meinu-quanfa",
	"difficult":	2,
	"team":		11,
]),
([	"family":	"ª™…Ω≈…", //13-hs1
	"force" :	"zixia-gong",
	"dodge" :	"huashan-shenfa",
	"parry":	"huashan-jianfa",
	"sword" :	"huashan-jianfa",
	"cuff" : 	"poyu-quan",
	"difficult":	3,
	"team":		12,
]),
([	"family":	"ª™…Ω≈…", //14-hs2
	"force" :	"zixia-gong",
	"dodge" :	"huashan-shenfa",
	"parry":	"chongling-jian",
	"sword" :	"chongling-jian",
	"cuff" : 	"poyu-quan",
	"difficult":	1,
	"team":		13,
]),
([	"family":	"ª™…Ω≈…", //15-hs3
	"force" :	"zixia-gong",
	"dodge" :	"huashan-shenfa",
	"parry":	"fanliangyi-dao",
	"blade" :	"fanliangyi-dao",
	"cuff" : 	"poyu-quan",
	"difficult":	2,
	"team":		14,
]),
([	"family":	"¿•¬ÿ≈…", //16-kl1
	"force" :	"xuantian-wuji",
	"dodge" :	"taxue-wuhen",
	"parry":	"liangyi-jian",
	"sword" :	"liangyi-jian",
	"strike" : 	"kunlun-zhang",
	"difficult":	3,
	"team":		15,
]),
([	"family":	"¿•¬ÿ≈…", //17-kl2
	"force" :	"xuantian-wuji",
	"dodge" :	"taxue-wuhen",
	"parry":	"xunlei-jian",
	"sword" :	"xunlei-jian",
	"leg" : 	"chuanyun-tui",
	"difficult":	2,
	"team":		16,
]),
([	"family":	"¿•¬ÿ≈…", //18-kl3
	"force" :	"xuantian-wuji",
	"dodge" :	"taxue-wuhen",
	"parry":	"xunlei-jian",
	"sword" :	"xunlei-jian",
	"cuff" : 	"zhentian-quan",
	"difficult":	2,
	"team":		17,
]),
([	"family":	"¿•¬ÿ≈…", //19-kl4
	"force" :	"xuantian-wuji",
	"dodge" :	"taxue-wuhen",
	"parry":	"mantian-huayu",
	"throwing" :	"mantian-huayu",
	"strike" : 	"kunlun-zhang",
	"difficult":	1,
	"team":		18,
]),
([	"family":	"√˜ΩÃ", //20-mj1
	"force" :	"shenghuo-shengong",
	"dodge" :	"piaoyi-shenfa",
	"parry":	"qiankun-danuoyi",
	"dagger" :	"shenghuo-lingfa",
	"cuff" : 	"shenghuo-lingfa",
	"difficult":	2,
	"team":		19,
]),
([	"family":	"√˜ΩÃ", //21-mj2
	"force" :	"shenghuo-shengong",
	"dodge" :	"piaoyi-shenfa",
	"parry":	"qiankun-danuoyi",
	"dagger" :	"shenghuo-lingfa",
	"cuff" : 	"qishang-quan",
	"difficult":	3,
	"team":		20,
]),
([	"family":	"√˜ΩÃ", //22-mj3
	"force" :	"shenghuo-shengong",
	"dodge" :	"piaoyi-shenfa",
	"parry":	"lieyan-dao",
	"blade" :	"lieyan-dao",
	"hand" : 	"yingzhua-shou",
	"difficult":	1,
	"team":		21,
]),
([	"family":	"√˜ΩÃ", //23-mj4
	"force" :	"shenghuo-shengong",
	"dodge" :	"piaoyi-shenfa",
	"parry":	"liehuo-jian",
	"sword" :	"liehuo-jian",
	"strike" : 	"hanbing-mianzhang",
	"difficult":	1,
	"team":		22,
]),
([	"family":	"√˜ΩÃ", //24-mj5
	"force" :	"shenghuo-shengong",
	"dodge" :	"piaoyi-shenfa",
	"parry":	"duoming-jinhua",
	"throwing" : 	"duoming-jinhua",
	"strike" :	"hanbing-mianzhang",
	"difficult":	1,
	"team":		23,
]),
([	"family":	"π√À’ƒΩ»›", //25-mr1
	"force" :	"shenyuan-gong",
	"dodge" :	"yanling-shenfa",
	"parry":	"douzhuan-xingyi",
	"sword" :	"murong-jianfa",
	"finger" : 	"canhe-zhi",
	"difficult":	3,
	"team":		24,
]),
([	"family":	"π√À’ƒΩ»›", //26-mr2
	"force" :	"shenyuan-gong",
	"dodge" :	"yanling-shenfa",
	"parry":	"douzhuan-xingyi",
	"blade" :	"murong-daofa",
	"strike" : 	"xingyi-zhang",
	"difficult":	2,
	"team":		25,
]),
([	"family":	"…Ÿ¡÷≈…", //27-sl1
	"force" :	"yijin-jing",
	"dodge" :	"shaolin-shenfa",
	"parry":	"ranmu-daofa",
	"blade" :	"ranmu-daofa",
	"leg" : 	"ruying-suixingtui",
	"hand":		"qianye-shou",
	"difficult":	3,
	"team":		26,
]),
([	"family":	"…Ÿ¡÷≈…", //28-sl2
	"force" :	"yijin-jing",
	"dodge" :	"shaolin-shenfa",
	"parry":	"zui-gun",
	"club" : 	"zui-gun",
	"cuff":		"jingang-quan",
	"strike" :	"banruo-zhang",
	"difficult":	2,
	"team":		27,
]),
([	"family":	"…Ÿ¡÷≈…", //29-sl3
	"force" :	"yijin-jing",
	"dodge" :	"shaolin-shenfa",
	"parry":	"riyue-bian",
	"whip" :	"riyue-bian",
	"finger" : 	"yizhi-chan",
	"claw" : 	"longzhua-gong",
	"difficult":	3,
	"team":		28,
]),
([	"family":	"…Ÿ¡÷≈…", //30-sl4
	"force" :	"yijin-jing",
	"dodge" :	"shaolin-shenfa",
	"parry":	"xiuluo-dao",
	"blade" :	"xiuluo-dao",
	"strike" : 	"sanhua-zhang",
	"finger":	"nianhua-zhi",
	"difficult":	2,
	"team":		29,
]),
([	"family":	"…Ÿ¡÷≈…", //31-sl5
	"force" :	"yijin-jing",
	"dodge" :	"shaolin-shenfa",
	"parry":	"damo-jian",
	"sword" :	"damo-jian",
	"leg" : 	"shaolin-tantui",
	"hand":		"fengyun-shou",
	"difficult":	1,
	"team":		30,
]),
([	"family":	"…Ÿ¡÷≈…", //32-sl6
	"force" :	"yijin-jing",
	"dodge" :	"shaolin-shenfa",
	"parry":	"pudu-zhang",
	"staff" :	"pudu-zhang",
	"claw" : 	"jimie-zhua",
	"finger":	"mohe-zhi",
	"difficult":	1,
	"team":		31,
]),
([	"family":	"…Ÿ¡÷≈…", //33-sl7
	"force" :	"yijin-jing",
	"dodge" :	"shaolin-shenfa",
	"parry":	"weituo-chu",
	"club" :	"weituo-chu",
	"cuff" : 	"luohan-quan",
	"finger":	"wuxiang-zhi",
	"difficult":	3,
	"team":		32,
]),
([	"family":	"…Ÿ¡÷≈…", //34-sl8
	"force" :	"yijin-jing",
	"dodge" :	"shaolin-shenfa",
	"parry":	"cibei-dao",
	"blade" :	"cibei-dao",
	"leg" : 	"shaolin-tantui",
	"hand":		"fengyun-shou",
	"difficult":	1,
	"team":		33,
]),
([	"family":	"…Ÿ¡÷≈…", //35-sl9
	"force" :	"yijin-jing",
	"dodge" :	"shaolin-shenfa",
	"parry":	"wuchang-zhang",
	"staff" :	"wuchang-zhang",
	"claw" : 	"jimie-zhua",
	"finger":	"mohe-zhi",
	"difficult":	1,
	"team":		34,
]),
([	"family":	"…Ò¡˙ΩÃ", //36-sld1
	"force" :	"dulong-dafa",
	"dodge" :	"youlong-shenfa",
	"parry":	"tenglong-bifa",
	"dagger" :	"tenglong-bifa",
	"strike" : 	"huagu-mianzhang",
	"difficult":	3,
	"team":		35,
]),
([	"family":	"…Ò¡˙ΩÃ", //37-sld2
	"force" :	"dulong-dafa",
	"dodge" :	"youlong-shenfa",
	"parry":	"canglang-goufa",
	"hook" :	"canglang-goufa",
	"leg" : 	"shenlong-tuifa",
	"difficult":	1,
	"team":		36,
]),
([	"family":	"·‘…Ω≈…", //38-ss1
	"force" :	"hanbing-zhenqi",
	"dodge" :	"zhongyuefeng",
	"parry":	"songshan-jian",
	"sword" :	"songshan-jian",
	"hand" : 	"songyang-shou",
	"difficult":	2,
	"team":		37,
]),
([	"family":	"·‘…Ω≈…", //39-ss2
	"force" :	"hanbing-zhenqi",
	"dodge" :	"zhongyuefeng",
	"parry":	"songshan-jian",
	"sword" :	"songshan-jian",
	"strike" : 	"hanbing-shenzhang",
	"difficult":	3,
	"team":		38,
]),
([	"family":	"·‘…Ω≈…", //40-ss3
	"force" :	"hanbing-zhenqi",
	"dodge" :	"zhongyuefeng",
	"parry":	"songyang-bian",
	"whip" :	"songyang-bian",
	"hand" : 	"songyang-shou",
	"difficult":	1,
	"team":		39,
]),
([	"family":	"Ã“ª®µ∫", //41-thd1
	"force" :	"bihai-chaosheng",
	"dodge" :	"suibo-zhuliu",
	"parry":	"tanzhi-shentong",
	"throwing" :	"tanzhi-shentong",
	"finger" : 	"tanzhi-shentong",
	"difficult":	3,
	"team":		40,
]),
([	"family":	"Ã“ª®µ∫", //42-thd2
	"force" :	"bihai-chaosheng",
	"dodge" :	"suibo-zhuliu",
	"parry":	"yuxiao-jian",
	"sword" :	"yuxiao-jian",
	"leg" : 	"xuanfeng-tui",
	"difficult":	1,
	"team":		41,
]),
([	"family":	"Ã“ª®µ∫", //43-thd3
	"force" :	"bihai-chaosheng",
	"dodge" :	"suibo-zhuliu",
	"parry":	"yuxiao-jian",
	"sword" :	"yuxiao-jian",
	"strike" : 	"luoying-zhang",
	"difficult":	1,
	"team":		42,
]),
([	"family":	"Ã“ª®µ∫", //44-thd4
	"force" :	"bihai-chaosheng",
	"dodge" :	"suibo-zhuliu",
	"parry":	"yuxiao-jian",
	"sword" :	"yuxiao-jian",
	"hand" : 	"lanhua-shou",
	"difficult":	2,
	"team":		43,
]),
([	"family":	"ÃÏ¡˙À¬", //45-tls1
	"force" :	"kurong-changong",
	"dodge" :	"tianlong-xiang",
	"parry":	"kurong-changong",
	"whip" :	"cihang-bian",
	"strike" : 	"kurong-changong",
	"difficult":	2,
	"team":		44,
]),
([	"family":	"ÃÏ¡˙À¬", //46-tls2
	"force" :	"kurong-changong",
	"dodge" :	"tianlong-xiang",
	"parry":	"kurong-changong",
	"staff" :	"yiyang-zhi",
	"finger" : 	"yiyang-zhi",
	"difficult":	3,
	"team":		45,
]),
([	"family":	"ÃÏ¡˙À¬", //47-tls3
	"force" :	"qiantian-yiyang",
	"dodge" :	"tianlong-xiang",
	"parry":	"yiyang-zhi",
	"staff" :	"yiyang-zhi",
	"finger" : 	"yiyang-zhi",
	"difficult":	2,
	"team":		46,
]),
([	"family":	"ÃÏ¡˙À¬", //48-tls4
	"force" :	"qiantian-yiyang",
	"dodge" :	"tianlong-xiang",
	"parry":	"duanjia-jianfa",
	"sword" :	"duanjia-jianfa",
	"strike" : 	"qingyan-zhang",
	"difficult":	1,
	"team":		47,
]),
([	"family":	"ÃÏ¡˙À¬", //49-tls5
	"force" :	"qiantian-yiyang",
	"dodge" :	"tianlong-xiang",
	"parry":	"pangen-fu",
	"axe" :		"pangen-fu",
	"cuff" : 	"duanjia-quan",
	"difficult":	1,
	"team":		48,
]),
([	"family":	"Ã˙’∆∞Ô", //50-tz1
	"force" :	"guiyuan-tunafa",
	"dodge" :	"shuishangpiao",
	"parry":	"tiezhang-zhangfa",
	"blade" :	"liuye-daofa",
	"strike" : 	"tiezhang-zhangfa",
	"difficult":	2,
	"team":		49,
]),
([	"family":	"Œ‰µ±≈…", //51-wd1
	"force" :	"yinyun-ziqi",
	"dodge" :	"tiyunzong",
	"parry":	"taiji-jian",
	"sword" :	"taiji-jian",
	"cuff" : 	"taiji-quan",
	"difficult":	3,
	"team":		50,
]),
([	"family":	"Œ‰µ±≈…", //52-wd2
	"force" :	"yinyun-ziqi",
	"dodge" :	"tiyunzong",
	"parry":	"xuanxu-daofa",
	"blade" :	"xuanxu-daofa",
	"strike" : 	"zhenshan-mianzhang",
	"difficult":	1,
	"team":		51,
]),
([	"family":	"Œ‰µ±≈…", //53-wd3
	"force" :	"yinyun-ziqi",
	"dodge" :	"tiyunzong",
	"parry":	"taiji-jian",
	"blade" :	"taiji-jian",
	"hand" : 	"juehu-shou",
	"difficult":	2,
	"team":		52,
]),
([	"family":	"Œ‰µ±≈…", //54-wd4
	"force" :	"yinyun-ziqi",
	"dodge" :	"tiyunzong",
	"parry":	"xuanxu-daofa",
	"blade" :	"xuanxu-daofa",
	"cuff" : 	"wudang-quan",
	"difficult":	1,
	"team":		53,
]),
([	"family":	"–«Àﬁ≈…", //55-xx1
	"force" :	"huagong-dafa",
	"dodge" :	"zhaixingshu",
	"parry":	"chousui-zhang",
	"staff" :	"tianshan-zhang",
	"strike" : 	"chousui-zhang",
	"difficult":	2,
	"team":		54,
]),
([	"family":	"–«Àﬁ≈…", //56-xx2
	"force" :	"huagong-dafa",
	"dodge" :	"zhaixingshu",
	"parry":	"tianshan-zhang",
	"blade" :	"tianshan-zhang",
	"claw" : 	"sanyin-zhua",
	"difficult":	1,
	"team":		55,
]),
([	"family":	"–«Àﬁ≈…", //57-xx3
	"force" :	"huagong-dafa",
	"dodge" :	"pixie-jian",
	"parry":	"pixie-jian",
	"sword" :	"pixie-jian",
	"strike" : 	"chousui-zhang",
	"difficult":	3,
	"team":		56,
]),
([	"family":	"¥Û¬÷À¬", //58-xs1
	"force" :	"longxiang-boruo",
	"dodge" :	"yuxue-dunxing",
	"parry":	"xiangfu-lun",
	"hammer" :	"xiangfu-lun",
	"claw" : 	"tianwang-zhua",
	"difficult":	3,
	"team":		57,
]),
([	"family":	"¥Û¬÷À¬", //59-xs2
	"force" :	"longxiang-boruo",
	"dodge" :	"yuxue-dunxing",
	"parry":	"xuedao-jing",
	"blade" :	"xuedao-jing",
	"strike" : 	"huoyan-dao",
	"difficult":	2,
	"team":		58,
]),
([	"family":	"¥Û¬÷À¬", //60-xs3
	"force" :	"longxiang-boruo",
	"dodge" :	"yuxue-dunxing",
	"parry":	"wushang-dali",
	"staff" :	"wushang-dali",
	"hand" : 	"dashou-yin",
	"difficult":	1,
	"team":		59,
]),
});
