mapping *xuedao = ({
([     "id":"tanzhong", //穴道的拼音 id
       "name":"檀中穴", //穴道的全名
       "place":"chest", //穴道的位置(分为 head, chest, body, arm, leg)
       "flow":"任脉",   //穴道的经脉所属
       "eff": 2,       //威力参数(介于 0.1 到 2 之间)
//说明:奇经八脉加12经脉共计20脉,除去如手指，脚趾上不可能点到的穴位,任7,督9,十二经各5, 其他若干,共计100穴。
]),
 ([     "id":"zhongji",
        "name":"中极穴",
        "place":"body",
         "flow":"任脉",
        "eff": 16,
 
]),
 ([     "id":"guanyuan",
        "name":"关元穴",
        "place":"body",
         "flow":"任脉",
        "eff": 19,
 
]),
 ([     "id":"qihai",
        "name":"气海穴",
        "place":"body",
         "flow":"任脉",
        "eff": 20,
 
]),
 ([     "id":"shenque",
        "name":"神阙穴",
        "place":"body",
         "flow":"任脉",
        "eff": 18,
 
]),
 ([     "id":"zhongwan",
        "name":"中脘穴",
        "place":"body",
         "flow":"任脉",
        "eff": 14,
 
]),
 ([     "id":"tiantu",
        "name":"天突穴",
        "place":"head",
         "flow":"任脉",
        "eff": 16,
 
]),
 ([     "id":"changqiang",
        "name":"长强穴",
        "place":"body",
         "flow":"督脉",
        "eff": 14,
 
]),
 ([     "id":"yaojianguan",
        "name":"腰阳关穴",
        "place":"body",
         "flow":"督脉",
        "eff": 17,
 
]),
 ([     "id":"mingmen",
        "name":"命门穴",
        "place":"body",
         "flow":"督脉",
        "eff": 20,
 
]),
 ([     "id":"zhiyang",
        "name":"至阳穴",
        "place":"body",
         "flow":"督脉",
        "eff": 12,
 
]),
 ([     "id":"shenzhu",
        "name":"身柱穴",
        "place":"body",
         "flow":"督脉",
        "eff": 11,
 
]),
 ([     "id":"dazhui",
        "name":"大椎穴",
        "place":"head",
         "flow":"督脉",
        "eff": 10,
 
]),
 ([     "id":"yamen",
        "name":"哑门穴",
        "place":"head",
         "flow":"督脉",
        "eff": 15,
 
]),
 ([     "id":"fengfu",
        "name":"风府穴",
        "place":"head",
         "flow":"督脉",
        "eff": 18,
 
]),
 ([     "id":"baihui",
        "name":"百会穴",
        "place":"head",
         "flow":"督脉",
        "eff": 20,
 
]),
 ([     "id":"zhongfu",
        "name":"中府穴",
        "place":"chest",
         "flow":"手太阴肺经",
        "eff": 8,
]),
 ([     "id":"chize",
        "name":"尺泽穴",
        "place":"arm",
         "flow":"手太阴肺经",
        "eff": 2,
]), 
 ([     "id":"yunmen",
        "name":"云门穴",
        "place":"arm",
         "flow":"手太阴肺经",
        "eff": 11,
]),
 ([     "id":"lieque",
        "name":"列缺穴",
        "place":"arm",
         "flow":"手太阴肺经",
        "eff": 4,
]),
 ([     "id":"taiyuan",
        "name":"太渊穴",
        "place":"arm",
        "flow":"手太阴肺经",
        "eff": 3,
]),
 ([     "id":"shangyang",
        "name":"商阳穴",
        "place":"arm",
        "flow":"手阳明大肠经",
        "eff": 2,
]),
 ([     "id":"hegu",
        "name":"合谷穴",
        "place":"arm",
        "flow":"手阳明大肠经",
        "eff": 8,
]),
 ([     "id":"yingxiang",
        "name":"迎香穴",
        "place":"head",
        "flow":"手阳明大肠经",
        "eff": 12,
]),
 ([     "id":"tianding",
        "name":"天鼎穴",
        "place":"chest",
         "flow":"手阳明大肠经",
        "eff": 9,
]),
 ([     "id":"quci",
        "name":"曲池穴",
        "place":"arm",
        "flow":"手阳明大肠经",
        "eff": 8,
]),
 ([     "id":"chengqi",
        "name":"承泣穴",
        "place":"head",
        "flow":"足阳明胃经",
        "eff": 11,
 
]),
 ([     "id":"xiaguan",
        "name":"下关穴",
        "place":"head",
        "flow":"足阳明胃经",
        "eff": 14,
 
]),
 ([     "id":"liangmen",
        "name":"梁门穴",
        "place":"body",
        "flow":"足阳明胃经",
        "eff": 17,
 
]),
 ([     "id":"liangqiu",
        "name":"梁丘穴",
        "place":"leg",
        "flow":"足阳明胃经",
        "eff": 7,
 
]),
 ([     "id":"zusanli",
        "name":"足三里穴",
        "place":"leg",
        "flow":"足阳明胃经",
        "eff": 5,
 
]),
 ([     "id":"sanyinjiao",
        "name":"三阴交穴",
        "place":"leg",
        "flow":"足太阴脾经",
        "eff": 8,
 
]),
 ([     "id":"yinlingquan",
        "name":"阴陵泉穴",
        "place":"leg",
        "flow":"足太阴脾经",
        "eff": 11,
 
]),
 ([     "id":"xuehai",
        "name":"血海穴",
        "place":"leg",
        "flow":"足太阴脾经",
        "eff": 13,
 
]),
 ([     "id":"xiongxiang",
        "name":"胸乡穴",
        "place":"chest",
        "flow":"足太阴脾经",
        "eff": 6,
 
]),
 ([     "id":"fuai",
        "name":"服哀穴",
        "place":"head",
        "flow":"足太阴脾经",
        "eff": 3,
 
]),
 ([     "id":"tongli",
        "name":"通里穴",
        "place":"arm",
        "flow":"手少阴心经",
        "eff": 5,
 
]),
 ([     "id":"shenmen",
        "name":"神门穴",
        "place":"arm",
        "flow":"手少阴心经",
        "eff": 2,
 
]),
 ([     "id":"qingling",
        "name":"青灵穴",
        "place":"arm",
        "flow":"手少阴心经",
        "eff": 3,
 
]),
 ([     "id":"jiquan",
        "name":"极泉穴",
        "place":"arm",
        "flow":"手少阴心经",
        "eff": 5,
 
]),
 ([     "id":"linghai",
        "name":"灵海穴",
        "place":"arm",
        "flow":"手少阴心经",
        "eff": 5,
 
]),
 ([     "id":"tianzhong",
        "name":"天宗穴",
        "place":"chest",
        "flow":"手太阳小肠经",
        "eff": 15,
 
]),
 ([     "id":"tinggong",
        "name":"听宫穴",
        "place":"head",
        "flow":"手太阳小肠经",
        "eff": 4,
 
]),
 ([     "id":"jianzhongyu",
        "name":"肩中俞穴",
        "place":"arm",
        "flow":"手太阳小肠经",
        "eff": 12,
 
]),
 ([     "id":"jianwaiyu",
        "name":"肩外俞穴",
        "place":"arm",
        "flow":"手太阳小肠经",
        "eff": 16,
 
]),
 ([     "id":"jianzhen",
        "name":"肩贞穴",
        "place":"arm",
        "flow":"手太阳小肠经",
        "eff": 7,
 
]),
 ([     "id":"jingming",
        "name":"睛明穴",
        "place":"head",
        "flow":"足太阳膀胱经",
        "eff": 4,
 
]),
 ([     "id":"zanzhu",
        "name":"攒竹穴",
        "place":"head",
        "flow":"足太阳膀胱经",
        "eff": 1,
 
]),
 ([     "id":"tianzhu",
        "name":"天柱穴",
        "place":"head",
        "flow":"足太阳膀胱经",
        "eff": 13,
 
]),
 ([     "id":"gaohuang",
        "name":"膏肓穴",
        "place":"leg",
        "flow":"足太阳膀胱经",
        "eff": 9,
 
]),
 ([     "id":"chengshan",
        "name":"承山穴",
        "place":"leg",
        "flow":"足太阳膀胱经",
        "eff": 2,
 
]),
 ([     "id":"yongquan",
        "name":"涌泉穴",
        "place":"leg",
        "flow":"足少阴肾经",
        "eff": 17,
 
]),
 ([     "id":"fuliu",
        "name":"复溜穴",
        "place":"leg",
        "flow":"足少阴肾经",
        "eff": 9,
 
]),
 ([     "id":"rangu",
        "name":"然谷穴",
        "place":"leg",
        "flow":"足少阴肾经",
        "eff": 5,
 
]),
 ([     "id":"yingu",
        "name":"陰谷穴",
        "place":"body",
        "flow":"足少阴肾经",
        "eff": 4,
 
]),
 ([     "id":"taixi",
        "name":"太溪穴",
        "place":"body",
        "flow":"足少阴肾经",
        "eff": 17,
 
]),
 ([     "id":"quze",
        "name":"曲泽穴",
        "place":"leg",
        "flow":"手厥阴心包经",
        "eff": 6,
 
]),
 ([     "id":"",
        "name":"中冲穴",
        "place":"",
        "flow":"手厥阴心包经",
        "eff": 5,
 
]),
 ([     "id":"laogong",
        "name":"劳宫穴",
        "place":"arm",
        "flow":"手厥阴心包经",
        "eff": 13,
 
]),
 ([     "id":"neiguan",
        "name":"内关穴",
        "place":"arm",
        "flow":"手厥阴心包经",
        "eff": 2,
 
]),
 ([     "id":"jianshi",
        "name":"间使穴",
        "place":"arm",
        "flow":"手厥阴心包经",
        "eff": 5,
 
]),
 ([     "id":"waiguan",
        "name":"外关穴",
        "place":"arm",
        "flow":"手少阳三焦经",
        "eff": 2,
 
]),
 ([     "id":"zhigou",
        "name":"支沟穴",
        "place":"arm",
        "flow":"手少阳三焦经",
        "eff": 3,
 
]),
 ([     "id":"ermen",
        "name":"耳门穴",
        "place":"head",
        "flow":"手少阳三焦经",
        "eff": 8,
 
]),
 ([     "id":"yifeng",
        "name":"翳风穴",
        "place":"head",
        "flow":"手少阳三焦经",
        "eff": 1,
 
]),
 ([     "id":"sizhukong",
        "name":"丝竹空穴",
        "place":"head",
        "flow":"手少阳三焦经",
        "eff": 4,
 
]),
 ([     "id":"tinghui",
        "name":"听会穴",
        "place":"head",
        "flow":"足少阳胆经",
        "eff": 4,
 
]),
 ([     "id":"yangbai",
        "name":"阳白穴",
        "place":"head",
         "flow":"足少阳胆经",
        "eff": 7,
 
]),
 ([     "id":"fengchi",
        "name":"风池穴",
        "place":"head",
         "flow":"足少阳胆经",
        "eff": 13,
 
]),
 ([     "id":"jianjing",
        "name":"肩井穴",
        "place":"chest",
         "flow":"足少阳胆经",
        "eff": 19,
 
]),
 ([     "id":"fengshi",
        "name":"风市穴",
        "place":"leg",
         "flow":"足少阳胆经",
        "eff": 16,
 
]),
 ([     "id":"qimen",
        "name":"期门穴",
        "place":"chest",
         "flow":"足厥阳肝经",
        "eff": 19,
 
]),
 ([     "id":"dadun",
        "name":"大敦穴",
        "place":"leg",
         "flow":"足厥阳肝经",
        "eff": 4,
 
]),
 ([     "id":"xingjian",
        "name":"行间穴",
        "place":"leg",
         "flow":"足厥阳肝经",
        "eff": 3,
 
]),
 ([     "id":"taichong",
        "name":"太冲穴",
        "place":"body",
         "flow":"足厥阳肝经",
        "eff": 11,
 
]),
 ([     "id":"zhongfeng",
        "name":"中封穴",
        "place":"body",
         "flow":"足厥阳肝经",
        "eff": 7,
 
]),
 ([     "id":"huiyin",
        "name":"会阴穴",
        "place":"body",
         "flow":"冲脉",
        "eff": 9,
]),
 ([     "id":"yinjiao",
        "name":"阴交穴",
        "place":"body",
         "flow":"冲脉",
        "eff": 12,
]),
 ([     "id":"qichong",
        "name":"气冲穴",
        "place":"body",
         "flow":"冲脉",
        "eff": 15,
]),
 ([     "id":"zhongzhu",
        "name":"中注穴",
        "place":"body",
         "flow":"冲脉",
        "eff": 12,
]),
 ([     "id":"youmen",
        "name":"幽门穴",
        "place":"body",
         "flow":"冲脉",
        "eff": 18,
]),
 ([     "id":"shangqu",
        "name":"商曲穴",
        "place":"arm",
         "flow":"冲脉",
        "eff": 11,
]),
 ([     "id":"wushu",
        "name":"五枢穴",
        "place":"head",
         "flow":"带脉",
        "eff": 19,
]),
 ([     "id":"weidao",
        "name":"维道穴",
        "place":"body",
         "flow":"带脉",
        "eff": 3,
]),
 ([     "id":"zhubin",
        "name":"筑宾穴",
        "place":"body",
         "flow":"阴维脉",
        "eff": 9,
]),
 ([     "id":"fushe",
        "name":"府舍穴",
        "place":"chest",
         "flow":"阴维脉",
        "eff": 12,
]),
 ([     "id":"daheng",
        "name":"大横穴",
        "place":"body",
         "flow":"阴维脉",
        "eff": 7,
]),
 ([     "id":"tiantu",
        "name":"天突穴",
        "place":"head",
         "flow":"阴维脉",
        "eff": 19,
]),
 ([     "id":"jinmen",
        "name":"金门穴",
        "place":"body",
         "flow":"阳维脉",
        "eff": 5,
]),
 ([     "id":"yangjiao",
        "name":"阳交穴",
        "place":"body",
         "flow":"阳维脉",
        "eff": 18,
]),
 ([     "id":"zhengying",
        "name":"正营穴",
        "place":"body",
         "flow":"阳维脉",
        "eff": 8,
]),
 ([     "id":"chengling",
        "name":"承灵穴",
        "place":"body",
         "flow":"阳维脉",
        "eff": 9,
]),
 ([     "id":"tianliao",
        "name":"天寥穴",
        "place":"head",
         "flow":"阳维脉",
        "eff": 17,
]),
 ([     "id":"zhaohai",
        "name":"照海穴",
        "place":"body",
         "flow":"阴跷脉",
        "eff": 4,
]),
([     "id":"jiaoxin",
        "name":"交信穴",
        "place":"body",
         "flow":"阴跷脉",
        "eff": 6,
]),
([     "id":"fuyang",
        "name":"跗阳穴",
        "place":"leg",
         "flow":"阳跷脉",
        "eff": 14,
]),
([     "id":"shenmai",
        "name":"审脉穴",
        "place":"body",
         "flow":"阳跷脉",
        "eff": 12,
]),
([     "id":"pushen",
        "name":"仆参穴",
        "place":"body",
         "flow":"阳跷脉",
        "eff": 4,
]),
([     "id":"jugu",
        "name":"巨骨穴",
        "place":"body",
         "flow":"阳跷脉",
        "eff": 20,
]),
([     "id":"dicang",
        "name":"地仓穴",
        "place":"body",
         "flow":"阳跷脉",
        "eff": 7,
]),
});
