mapping get_party_string(string id);
mapping get_party_int(int i);
mapping *party_list = ({
	(["party":	 "wd", // 门派简称
	  "party-name":       "武当", // 门派中文名称
	  "col":	""HIW"", // 门派颜色
	  "shen":	"正",//正邪
	  "lineup":	"zhenwu-qijiezhen",//阵法
	  "lineup-name":	"真武七截阵",//阵法名字
	]), 
	(["party":	 "hs", 
	  "party-name":       "华山", 
	  "col":	""HIM"",
	  "shen":	"正",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]), 
	(["party":	 "ss", 
	  "party-name": "嵩山", 
	  "col":	""HIM"",
	  "shen":	"邪",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]), 
	(["party":	 "gm", 
	  "party-name": "古墓", 
	  "col":	""HIY"",
	  "shen":	"中",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]), 
	(["party":	 "gb", 
	  "party-name": "丐帮", 
	  "col":	""HIW"",
	  "shen":	"正",
	  "lineup":	"dagou-zhen",
	  "lineup-name":	"打狗阵",
	]), 
	(["party":	 "tz", 
	  "party-name": "铁掌", 
	  "col":	""HIR"",
	  "shen":	"邪",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]), 
	(["party":	 "dls", 
	  "party-name": "大轮寺", 
	  "col":	""HIY"",
	  "shen":	"邪",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]),
	(["party":	 "mr", 
	  "party-name": "慕容", 
	  "col":	""HIG"",
	  "shen":	"中",
	  "lineup":	"xingyi-jianzhen",
	  "lineup-name":	"星移剑阵",
	]), 
	(["party":	 "sld", 
	  "party-name": "神龙岛", 
	  "col":	""HIC"",
	  "shen":	"邪",
	  "lineup":	"shenlong-wudizhen",
	  "lineup-name":	"神龙无敌阵",
	]),
	(["party":	 "xx", 
	  "party-name": "星宿", 
	  "col":	""HIB"",
	  "shen":	"邪",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]),
	(["party":	 "em", 
	  "party-name": "峨嵋", 
	  "col":	""HIM"",
	  "shen":	"正",
	  "lineup":	"linji-jianzhen",
	  "lineup-name":	"临济剑阵",
	]),
	(["party":	 "mj", 
	  "party-name": "明教", 
	  "col":	""WHT"",
	  "shen":	"中",
	  "lineup":	"shenghuo-fumozhen",
	  "lineup-name":	"圣火伏魔阵",
	]),
	(["party":	 "thd", 
	  "party-name": "桃花岛", 
	  "col":	""HIG"",
	  "shen":	"中",
	  "lineup":	"qimen-baguazhen",
	  "lineup-name":	"奇门八卦阵",
	]),
	(["party":	 "tls", 
	  "party-name": "天龙寺", 
	  "col":	""HIY"",
	  "shen":	"正",
	  "lineup":	"liumai-jianzhen",
	  "lineup-name":	"六脉剑阵",
	]),
	(["party":	 "sl", 
	  "party-name": "少林", 
	  "col":	""HIR"",
	  "shen":	"正",
	  "lineup":	"fumoquan-zhen",
	  "lineup-name":	"伏魔圈阵",
	]),
	(["party":	 "kl", 
	  "party-name": "昆仑", 
	  "col":	""HIB"",
	  "shen":	"中",
	  "lineup":	"tiangang-beidouzhen",
	  "lineup-name":	"天罡北斗阵",
	]),
	(["party":	 "9y", 
	  "party-name": "九阴", 
	  "col":	""HIB"",
	  "shen":	"中",
	  "lineup":	"tiangang-beidouzhen",
	  "lineup-name":	"天罡北斗阵",
	]),
	(["party":	 "hmg", 
	  "party-name": "蛤蟆功", 
	  "col":	""HIW"",
	  "shen":	"中",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]),
	(["party":	 "pxj", 
	  "party-name": "辟邪剑", 
	  "col":	""HIC"",
	  "shen":	"中",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]),
	(["party":	 "jsj", 
	  "party-name": "金蛇剑", 
	  "col":	""YEL"",
	  "shen":	"中",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]),
});
mapping get_party_string(string id)
{
	int i;
	for(i=0;i<sizeof(party_list);i++)
	{
	      if(party_list[i]["party"]==id)
	      		return party_list[i];
	}
	return 	(["party":	 "wm", 
	  "party-name": "无名门派", 
	  "col":	""HBYEL"",
	  "shen":	"中",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]);
}
mapping get_party_int(int i)
{
	if(i>0 && i<(sizeof(party_list)+1))
	      		return party_list[i-1];
	return 	(["party":	 "wm", 
	  "party-name": "无名门派", 
	  "col":	""HBYEL"",
	  "shen":	"中",
	  "lineup":	"wuxing-zhen",
	  "lineup-name":	"五行阵",
	]);
}
