mapping dls_desc = ([ "party" : "大轮寺",
                      "nickname" : "喇嘛活佛",
                      "desc"  : "身上披了一件藏僧袈裟，毛发好如牦牛一般，竟活脱脱一个喇嘛骑着牦牛的打扮。",
                      "say_desc" : "猪人五摔，我摔，我摔，我摔摔摔",
                      "question" : "掌门师傅鸠摩智曾与天龙高手比斗，用的一种奇怪的武器，是什么？",
                      "answer" : "藏香",
                      ]);
				
mapping em_desc = ([ "party" : "娥眉派",
                      "nickname" : "尼姑光头",
                      "desc"  : "仰望她的猪头，上面佛光闪闪，让人想起峨嵋山的大师们。",
                      "say_desc" : "看什么看，我这么漂亮的小尼姑也是随便看得的么？",
                      "question" : "峨嵋“静”字辈出家弟子中，谁是掌门师姐？",
                      "answer" : "静玄",
                      ]);	
	
mapping mr_desc = ([ "party" : "姑苏慕容",
                      "nickname" : "绣花枕头",
                      "desc"  : "她的猪肚上描龙绣凤，大有皇族气派，写着一行字“里面全是草”，怎么看怎么象苏州的慕容公子。",
                      "say_desc" : "我要当皇帝~~~，我要小汽车~~~~~，我要大楼房~~~~~",
                      "question" : "慕容一支是哪个民族的后裔啊？",
                      "answer" : "鲜卑",
                      ]);	

mapping gm_desc = ([ "party" : "古墓派",
                      "nickname" : "黯然消魂",
                      "desc"  : "她玉面素心，冷若冰霜，飘飘然如同小龙女重现江湖，略微更正一下，是“身材滚圆的小龙女”。",
                      "say_desc" : "猪奶奶我早绝了七情六欲啦，你个毛头小伙子色咪咪看着我干吗？",
                      "question" : "《玉女心经》分单数行功和双数行功，单数双数各称什么？",
                      "answer" : "阴进阳退",
                      ]);	

mapping hs_desc = ([ "party" : "华山派",
                      "nickname" : "卓越不群",
                      "desc"  : "她的后脑勺插着一面小旗帜，上面写着四个大字“卓（捉）越（岳）不群”。",
                      "say_desc" : "我是来捉岳不群那老贼的？岳不群呢？岳不群呢？",
                      "question" : "掌门师兄黄真大弟子叫什么名字呀？",
                      "answer" : "冯难敌",
                      ]);	
                      
mapping mj_desc = ([ "party" : "明教",
                      "nickname" : "烈火雄心",
                      "desc"  : "她浑身通红，仿佛如同熊熊火焰，背后还背了一个泡沫灭火器。",
                      "say_desc" : "熊熊烈火，焚我残躯？……怎么觉得好象烤乳猪",
                      "question" : "喜怒哀乐，皆归尘土，怜我世人，后面一句是什么？",
                      "answer" : "忧患实多",
                      ]);
                      
mapping sl_desc = ([ "party" : "少林派",
                      "nickname" : "吃斋念佛",
                      "desc"  : "她一脸慈祥，从来只吃斋念佛，即使有人欺负她，她也不会生气，只会用燃木刀法温柔的割下那个人的鼻子。",
                      "say_desc" : "善哉善哉，我一刀劈死你呀，我两刀劈死你呀。",
                      "question" : "即心即佛，即佛即心，心明识佛，识佛明心，后面四字真言是什么？",
                      "answer" : "离心非佛",
                      ]);                      	

mapping sld_desc = ([ "party" : "神龙教",
                      "nickname" : "蛇头",
                      "desc"  : "她自称来自东海神龙毒蛇之岛，是群蛇之头，后人称之曰“蛇头”。",
                      "say_desc" : "我只是神龙使者，叫我什么蛇头……，亏那个倒霉WIZ想得出来。",
                      "question" : "神龙教用来控制下属的丹药一般是什么？",
                      "answer" : "豹胎易筋丸",
                      ]);                   

mapping thd_desc = ([ "party" : "桃花岛",
                      "nickname" : "碧海噪音",
                      "desc"  : "她随身带着一只猪尾巴玉箫，吹起来米里吗拉，噪音高达两百分贝。",
                      "say_desc" : "黄药师就是用噪音来打击敌人的吧。",
                      "question" : "黄蓉这个精灵丫头留给瑛姑的三道题目中第三道题目是什么？",
                      "answer" : "鬼谷算题",
                      ]);  

mapping tls_desc = ([ "party" : "天龙寺",
                      "nickname" : "六指吉祥",
                      "desc"  : "她与众不同之处在于，她有六只蹄子，可以分别连六脉神剑。",
                      "say_desc" : "六脉神剑象不象星球大战里的激光剑？",
                      "question" : "天龙高僧中，单修炼中指中冲剑法的是谁？",
                      "answer" : "本观",
                      ]); 

mapping tz_desc = ([ "party" : "铁掌帮",
                      "nickname" : "拳击沙袋",
                      "desc"  : "她的猪尾巴上挂着一直沙袋，一直用自己的铁蹄晃悠着去掌击沙袋为乐。",
                      "say_desc" : "CUT JIJI是不行滴，恢复笔法威力是必然滴，铁掌是土匪出身滴。",
                      "question" : "铁掌帮主家族中排行第几？",
                      "answer" : "二",
                      ]);
                      
mapping wd_desc = ([ "party" : "武当派",
                      "nickname" : "太极神汉",
                      "desc"  : "她一脸神仙飘逸之色，不怒不喜，手举一块大牌子，上书“YUN LIFESAVE 1K GOLD，不活500”。",
                      "say_desc" : "Yun Lifesave咯，1K GOLD一次，不活500！！！",
                      "question" : "他强任他强，后面一句是什么呀？",
                      "answer" : "明月照大江",
                      ]);

mapping xx_desc = ([ "party" : "星宿派",
                      "nickname" : "纵火",
                      "desc"  : "她一脸邪笑，不断用双蹄摩擦生热产生一个火球，还嚷嚷“我要推啦，我可真要推啦”。",
                      "say_desc" : "一起来推火墙，哼哼哈息，我要学手倒立……",
                      "question" : "被摘星子所杀的我派师兄弟中一个胖子，排行第几？",
                      "answer" : "三",
                      ]);
                      
mapping gb_desc = ([ "party" : "丐帮",
                      "nickname" : "要饭叫花",
                      "desc"  : "她背着七、八十个麻袋，不断的捉着身上的虱子“猪奶奶我身上就这几两肉啦”。",
                      "say_desc" : "猪奶奶我身上就这几两肉啦……",
                      "question" : "洪帮主最想吃的一道御膳是什么？",
                      "answer" : "鸳鸯五珍脍",
                      ]);

mapping ss_desc = ([ "party" : "嵩山派",
                      "nickname" : "寒冰真气",
                      "desc"  : "她双掌之间冒着霜冷寒冰之色，仔细去看，原来身后背了一只迷你冰箱。",
                      "say_desc" : "五岳剑派，一点创意都没有，活该左老头做瞎子……",
                      "question" : "阻止刘正风金盆洗手的嵩山弟子是谁？",
                      "answer" : "史登达",
                      ]);
                      
mixed question2 = ({
			([ "question" : "第一个向杨过传授武功的人是谁？","answer" : "穆念慈"]),
			([ "question" : "春波碧草，晓寒深处，下一句是？","answer" : "相对浴红衣"]),
			([ "question" : "华山论剑前，洪七公自称生平杀过多少人？","answer" : "231"]),
			([ "question" : "郭靖第一个杀死的人是谁？","answer" : "陈玄风"]),
			([ "question" : "瑛姑姓什么？","answer" : "刘"]),
			([ "question" : "木婉清的座骑的名字是什么？","answer" : "黑玫瑰"]),
			([ "question" : "裘千仞出家后法号是什么？","answer" : "慈恩"]),
			([ "question" : "阿珂是谁的女儿？","answer" : "李自成"]),
			([ "question" : "金庸14部小说中最早的一部是是？","answer" : "书剑恩仇录"]),
			([ "question" : "“手握灵珠常奋笔”下一句是什么？","answer" : "心开天籁不吹箫"]),
			([ "question" : "“一住行窝几十年”下一句是什么？","answer" : "蓬头垢面走如癫"]),
			([ "question" : "“桃花影落飞神剑”的下一句是什么？","answer" : "碧海潮生按玉箫"]),
			([ "question" : "李文秀的师父是谁？","answer" : "陈达海"]),
			([ "question" : "林平之的外公是谁？","answer" : "王元霸"]),
			([ "question" : "杨过名“过”，他的字是什么？","answer" : "改之"]),
			([ "question" : "杨过在襄阳城下杀死的蒙古可汗名字是？","answer" : "蒙哥"]),
			([ "question" : "王罕的亲儿子是谁？","answer" : "桑昆"]),
			([ "question" : "铁木真的“安答”是谁？","answer" : "扎木合"]),
			([ "question" : "段誉的母亲的道号是什么？","answer" : "玉虚散人"]),
			([ "question" : "慕容复在冒充西夏一品堂武士时的化名是什么？","answer" : "李延宗"]),
			([ "question" : "韦小宝的女儿叫什么？","answer" : "韦双双"]),
			([ "question" : "杨康的妈妈是谁？","answer" : "包惜弱"]),
			([ "question" : "《侠客行》中，叮当的叔父叫甚么名字？","answer" : "丁不四"]),
			([ "question" : "双儿的籍贯是什么地方？","answer" : "湖州"]),
			([ "question" : "苗人凤的女儿名字是？","answer" : "苗若兰"]),
			([ "question" : "成吉思汗临死前一直念叨着两个什么字？","answer" : "英雄"]),
			([ "question" : "赵敏父亲是什么王？","answer" : "汝阳王"]),
			([ "question" : "丘处机斗江南七怪时候使用的拼命剑法是？","answer" : "同归剑法"]),
			([ "question" : "大理天龙寺的正式名称是什么？","answer" : "崇圣寺"]),
			([ "question" : "江南七怪中的老四是谁？","answer" : "南希仁"]),
			([ "question" : "萧峰的少林派师父是谁？","answer" : "玄苦"]),
			([ "question" : "杨过的情花毒用什么东西解了？","answer" : "断肠草"]),
			([ "question" : "侠客行最后一句是？","answer" : "白首太玄经"]),
			([ "question" : "金庸的真实姓名是甚么？","answer" : "查良镛"]),
			([ "question" : "丐帮的降龙十八掌的招式哪一招曾经用来划船？","answer" : "神龙摆尾"]),
			([ "question" : "杨过的父亲在一个什么地方死去？","answer" : "铁枪庙"]),
			([ "question" : "武当七侠中哪一位弟子被砍段手脚？","answer" : "俞岱岩"]),
			([ "question" : "柯镇恶外号是什么？","answer" : "飞天蝙蝠"]),
			([ "question" : "顺治在给康熙的《四十二章经》首页中写了句甚么话？","answer" : "永不加赋"]),
			([ "question" : "郭啸天是被谁杀死的？","answer" : "段天德"]),
			([ "question" : "为了向段延庆表明心迹，被慕容复所杀的部下是谁？","answer" : "包不同"]),
			([ "question" : "郭靖在蒙古被成吉思汗封了什么称号？","answer" : "金刀驸马"]),
			([ "question" : "丘处机与江南七怪在什么地方约会比武？","answer" : "烟雨楼"]),
			([ "question" : "梅超风是被谁打死的？","answer" : "欧阳峰"]),
			([ "question" : "一灯大师的原名是什么？","answer" : "段智兴"]),
		});
		
mixed food = ({
		([ "id" : "kaoya" , "name" : "烤鸭"]),
		([ "id" : "jitui" , "name" : "烤鸡腿"]),
		([ "id" : "yue bing" , "name" : "月饼"]),
		([ "id" : "baozi" , "name" : "包子"]),
		([ "id" : "maofeng" , "name" : "金顶毛峰"]),
		([ "id" : "miantang" , "name" : "面汤"]),
		([ "id" : "mantou" , "name" : "馒头"]),
		([ "id" : "goubuli baozi" , "name" : "狗不理包子"]),
		([ "id" : "dong shanyang" , "name" : "东山羊"]),
		([ "id" : "long chaoshoui" , "name" : "龙抄手"]),
		([ "id" : "yangrou paomo" , "name" : "羊肉泡馍"]),
		([ "id" : "shanji rou" , "name" : "山鸡肉"]),
		([ "id" : "feicui doufu" , "name" : "翡翠豆腐"]),
		([ "id" : "ban doufu" , "name" : "板豆腐"]),
		([ "id" : "doufu gan" , "name" : "豆腐干"]),
		([ "id" : "hamigua" , "name" : "哈密瓜"]),
		([ "id" : "ru lao" , "name" : "乳酪"]),
		([ "id" : "yangrou chuan" , "name" : "羊肉串"]),
		([ "id" : "nang" , "name" : "馕"]),
		([ "id" : "shao bing" , "name" : "烧饼"]),
		([ "id" : "you tiao" , "name" : "油条"]),
		([ "id" : "mahua bianzi" , "name" : "麻花辫子"]),
		([ "id" : "jian jiao" , "name" : "素煎饺"]),
		});